### ISSUE TITLE
Support for template tags

### ISSUE THREAD

**Issue by tkuhn** [peta-pico/nanobench#38]
to structure template list into different sections (one section per tag)

**Comment by vemonet** [comment]
It could also enable to filter per tag (only show templates from selected tag)

**Comment by tkuhn** [comment]
Done with c0cc6a7581132f96962452369697d3578ca4cdb7.

See example here (... nt:hasTag "Meta"): https://np.petapico.org/RAWHrBJRZgzpNQo0_vW9yXyw_k5vkS6YHOSjx-b52ATiU
