### ISSUE TITLE
Update docker image to 1.27

### ISSUE THREAD

**Issue by nicholsn** [peta-pico/nanobench#48]
When starting up nanobench from docker I saw the following message:

```
nanobench_1  | ----------------------------------------
nanobench_1  |                Nanobench
nanobench_1  | ----------------------------------------
nanobench_1  |  You are using version: 1.25-SNAPSHOT
nanobench_1  |  Latest public version: 1.27
nanobench_1  | ----------------------------------------
```

I tried running `docker compose pull` but a newer version wasn't pulled down and checking docker hub it looks like the last version was from a month ago. 

Does dockerhub need to be updated with the most recent 1.27 release?

**Comment by tkuhn** [comment]
I was indeed negligent with updating the Docker version. Sorry for that.

I just updated the Docker image on dockerhub. I hope it works now.
