### ISSUE TITLE
Allow to easily search in the Nanopublications I published

### ISSUE THREAD

**Issue by vemonet** [peta-pico/nanobench#54]
When we have a lot of nanopublications it starts to be hard to find specific nanopubs we published to update/delete them via the Nanobench

The **My Channel** page does not have a search option, and the **Search** page does not allow to filter to see only the Nanopublications I published

Would it be possible to add such feature? It could be extended to searching for the Nanopubs of other users, but in our use-case we are particularly interested by easily searching through the nanopubs we personally published

**Comment by tkuhn** [comment]
Thanks, @vemonet, for having solved this!
